#define MAINPREFIX z
#define PREFIX vetspetua

#include "script_version.hpp"

#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD

#define REQUIRED_VERSION 2.12

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(VET - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(VET - COMPONENT)
#endif
